############################################################
# https://github.com/leukipp/cortile/blob/main/config.toml #
############################################################

# Tiling will be enabled on application start if set to true (true | false).
tiling_enabled = false

# Initial tiling layout ("fullscreen" | "vertical-left" | "vertical-right" | "horizontal-top" | "horizontal-bottom").
tiling_layout = "vertical-right"

# Initial division of master-slave area (0.0 - 1.0).
proportion = 0.6

# Minimum division of master-slave area (0.0 - 1.0).
proportion_min = 0.1

# Maximum division of master-slave area (0.0 - 1.0).
proportion_max = 0.9

# How much to increment/decrement master-slave area (0.0 - 1.0).
proportion_step = 0.05

# Additional margin of the tiling area ([top, right, bottom, left])
edge_margin = [0, 0, 0, 0]

# Width and height of a hot-corner area within the edge corners (0 - 100).
edge_corner_size = 10

# Width or height of a hot-corner area within the edge centers (0 - 100).
edge_center_size = 100

# Maximum number of allowed master windows (0 - 10)
window_masters_max = 5

# Maximum number of allowed slave windows (1 - 10)
window_slaves_max = 5

# How much space should be left between windows (0 - 100).
window_gap_size = 4

# Window decorations will be removed if set to false (true | false).
window_decoration = false

# Regex in RE2 syntax for ignoring windows (['WM_CLASS', 'WM_NAME'] = ['ignore all windows with this class', 'but allow those with this name']).
# WM_CLASS string can be found by running 'xprop WM_CLASS'.
window_ignore = [
    ['nm.*', ''],
    ['gcr.*', ''],
    ['polkit.*', ''],
    ['wrapper.*', ''],
    ['lightdm.*', ''],
    ['blueman.*', ''],
    ['pavucontrol.*', ''],
    ['xfce4-display-settings.*', ''],
    ['firefox.*', '.*Mozilla Firefox'],
]

############################################################
[keys]        # Key symbols can be found by running 'xev'. #
############################################################

# Tile the current workspace.
tile = "mod1-T"

# Untile the current workspace.
untile = "mod1-U"

# Cycles through the available layouts.
layout_cycle = "mod1-C"

# Activates the fullscreen layout.
layout_fullscreen = "mod1-W"

# Activates the vertical-left layout.
layout_vertical_left = "mod1-Left"

# Activates the vertical-right layout.
layout_vertical_right = "mod1-Right"

# Activates the horizontal-top layout.
layout_horizontal_top = "mod1-Up"

# Activates the horizontal-bottom layout.
layout_horizontal_bottom = "mod1-Down"

# Make the active window as master.
master_make = "mod1-M"

# Increase the number of masters.
master_increase = "mod1-Plus"

# Decrease the number of masters.
master_decrease = "mod1-Minus"

# Increase the number of slaves.
slave_increase = "Control-Shift-KP_Add"

# Decrease the number of slaves.
slave_decrease = "Control-Shift-KP_Subtract"

# Increase the proportion of master-slave area.
proportion_increase = "mod1-l"

# Decrease the proportion of master-slave area.
proportion_decrease = "mod1-k"

# Moves focus to the next window.
window_next = "mod1-n"

# Moves focus to the previous window.
window_previous = "Control-Shift-KP_8"

############################################################
[corners]  # Action strings can also be external commands. #
############################################################

# Corner at top left
top_left = "layout_cycle"

# Corner at top center
top_center = "tile"

# Corner at top right
top_right = "master_make"

# Corner at center right
center_right = "proportion_increase"

# Corner at bottom right
bottom_right = "master_increase"

# Corner at bottom center
bottom_center = "untile"

# Corner at bottom left
bottom_left = "master_decrease"

# Corner at center left
center_left = "proportion_decrease"
